spring:
  jmx:
    enabled: true
  application:
    name: @project.name@

info:
  application:
    name: @project.name@
    version: @project.version@
    javaVersion: @java.version@

management:
  info:
    env:
      enabled: true
  # individually configures the endpoint identified by endpointId, which may define its own unique configurable properties
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      #group:
      show-details: always
#    prometheus:
#      enabled: true

  #globally configures common endpoint properties and the ways in which endpoints may be accessed.
  endpoints:
    jmx:
#      domain: ""
#      static-names: ""
      exposure:
        include: "*"
#        exclude: ""

    web:
      #base-path: /actuatornew
      exposure:
        include: "*"

