spring:
  jmx:
    enabled: true

  application:
    name: @project.name@

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
